# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    ports:
      - 3333:5555
    networks:
      - net

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox 
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    ports:
      - 5555:5555
    networks:
      - net

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - net

networks:
   net:

